spring:
  application:
    name: firstProj
  ai:
    # Disables the default ChatClient auto-configuration
    chat:
      client:
        enabled: true

    # Your Gemini configuration
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7

    # Your Groq configuration (Indented under spring.ai)
#    openai:
#      api-key: ${API_KEY}
#      base-url: https://openrouter.ai/api
#      chat:
#        options:
#          model: openrouter/free
#          temperature: 0.7