spring:
  application:
    name: firstProj

  ai:
    chat:
      client:
        enabled: true

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
            max-output-tokens: 500

    openai:
      api-key: dummy   # only if some dependency requires it

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG








